#- name: install portainer
#  docker_container:
#    name: portainer
#    image: portainer/portainer
#    state: started
#    ports:
#    - "9000:9000"
#    volumes:
#    - "/var/run/docker.sock:/var/run/docker.sock"

- name: install portainer
  shell: docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer

